name: Main workflow

on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Run gradlew build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
  lint:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Run gradlew lint
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: lint
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
  test:
    runs-on: ubuntu-20.04
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Run gradlew test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

